AWSTemplateFormatVersion: 2010-09-09
Description: Template IAM Admin User Group
Parameters:
  GroupName:
    Description: Name of the Group you want to create
    Type: String
    Default: AdminUser
Resources:
  AdminUser:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
Outputs:
  GroupName:
    Value: !Ref GroupName
    Description: The GroupName
    Export:
      Name: user-group-name
